version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rate_limiter:
    image: "rate-limiter"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_EXPIRE_TIMEOUT_SECONDS=10
    ports:
      - "8080:8080"